# Generated by Django 3.2.9 on 2021-11-26 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bubble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('live', '대기중'), ('confirmed', '확정됨'), ('expired', '만료됨')], default='live', max_length=10)),
                ('created', models.DateTimeField(auto_now=True)),
                ('time2meet', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('guest_max', models.PositiveSmallIntegerField(default=0)),
                ('title', models.TextField(max_length=50)),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('unit', models.PositiveSmallIntegerField(blank=True, choices=[(0, '밥'), (1, '술'), (2, '미팅'), (3, '스터디'), (4, '영화'), (5, '운동'), (6, '산책'), (7, '게임'), (8, '기타')])),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=200)),
                ('bubble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bubble.bubble')),
            ],
        ),
    ]
